### ISSUE TITLE
Download images

### ISSUE THREAD

**Issue by AndriusCTR** [cubiclesoft/ultimate-web-scraper#14]
Hello,

How can I download images, found during the scraping process? Let's say I am scraping html, and there are image links inside it, and I also want to download/save those images.

How can I do that?

Thank you

**Comment by cubiclesoft** [comment]
See:  https://github.com/cubiclesoft/ultimate-web-scraper#getting-started

The first code sample uses TagFilter to extract all 'a' tags with a 'href' attribute.  For images, you would do something similar but with `img[src]` instead.  The key is to convert the relative URLs extracted from the document to absolute URLs with `HTTP::ConvertRelativeToAbsoluteURL()`.

Once you have each absolute URL, reuse the WebBrowser object `$web` to start a new request for each image you want to download.  Since images can be fairly large, you could pass an `$options` array that uses a download callback as seen in the 'Example large file/content retrieval' code sample so that the data is directly written to disk.  If you are concerned about the correct HTTP Referer header being sent, then use the `clone` keyword to clone the original WebBrowser object before making each image request (e.g. `$web2 = clone $web;`).

Note that the above approach will download each image one at a time.  Depending on the number of images being retrieved, the [MultiAsyncHelper class](https://github.com/cubiclesoft/ultimate-web-scraper/blob/master/docs/multi_async_helper.md) may or may not be useful for performing multiple retrievals at the same time.  It's a slightly awkward class to use and most servers have concurrency and rate limits.  As a result, I don't use MultiAsyncHelper very often, which allows the scraper to stay below most awareness thresholds (i.e. I avoid upsetting sysadmins and getting IP blocked).  Your mileage may vary.
