### ISSUE TITLE
tag selector pattern bug in simple_html_dom.php

### ISSUE THREAD

**Issue by superdba218** [cubiclesoft/ultimate-web-scraper#16]
Line 722: [\w-:]
Line 386: [\w-:\*]

Fix pattern:
           Line 722: [\w-]
           Line 386: [\w-]

**Comment by cubiclesoft** [comment]
I am not the author of Simple HTML DOM.  The library is bundled with Ultimate Web Scraper Toolkit mostly for legacy reasons (e.g. the WebBrowser class still uses it for form extraction - I'll get around to re-writing that code sometime).

I recommend using the included [TagFilter class](https://github.com/cubiclesoft/ultimate-web-scraper/blob/master/docs/tag_filter.md) instead for new projects, which relies on robust state engines instead of fragile regexes to accomplish the same objective (i.e. extract and manipulate HTML and other tag-based documents), correctly parses CSS3 selectors (Simple HTML DOM only handles CSS2 selectors), is almost always many times faster than Simple HTML DOM and similar libraries, doesn't leak RAM all over the place, and fixes malformed HTML and can even be used to sanitize malicious HTML.

Simple HTML DOM was a great starting point for this project but TagFilter is superior in every way that matters.  TagFilter is not quite a drop-in replacement with existing code that relies on Simple HTML DOM, but it's pretty close.

**Comment by cubiclesoft** [comment]
I see what you are referring to in production on PHP 7.3.  However, your suggested fix would produce incorrect/invalid results.

I've committed the correct fix (but my text editor made a mess of the commit).  I wouldn't have bothered if WebBrowser wasn't still relying on the class.  Moving to TagFilter is the correct solution but I don't have time to deal with it.
