### ISSUE TITLE
This library will prevent IP blocking?

### ISSUE THREAD

**Issue by jpnathannew** [cubiclesoft/ultimate-web-scraper#17]
Hi, 

if continuously scrap one website firewall will block our IP. It was happen for me. is this library will prevent of blocking?

**Comment by cubiclesoft** [comment]
Some web hosts are configured to rate limit the number of incoming requests per minute per IP address.  You need to scale back the speed at which you request content.  Throw in a `sleep` statement after each request until the blocking stops.

By default, the library initiates a new connection every request and sends "Connection: close" in the request to the server.  It's also possible that you could be blocked by initiating too many connections in too short of a window.  A new connection guarantees a clean connectivity presence to the server but is fairly heavy-handed, especially since SSL/TLS takes system resources to set up and many sites use HTTPS.  Sending the "Connection: keep-alive" header allows for preserving the previous connection for reuse with another request to the same host later.  You'll have to pass the socket handle from the previous connection to the next connection.

Scraping comes with all kinds of difficulties.  This is already addressed in the main page for the toolkit.  There are creative ways around blocking but those avenues may actually have worse blocking metrics.  Backing off a lot tends to work pretty well.  Those blocking mechanisms are just there to keep you from abusing server resources.

The content you are looking for could be available in an alternate format (e.g. a ZIP file).  You could always try asking the server operator nicely if they have the data available in a convenient, consumable format and explain why you want the data.  Who knows?  They might be accommodating.
