### ISSUE TITLE
library can't process null,bolean values as postvars value

### ISSUE THREAD

**Issue by Cintrust** [cubiclesoft/ultimate-web-scraper#24]
https://github.com/cubiclesoft/ultimate-web-scraper/blob/10286a6b0c7fbda300f3f36c16bd102a6145c172/support/http.php#L1655

when null or bolean are passed as values to postvars parameter. an error message is emitted.
`PHP Warning:  Invalid argument supplied for foreach() in ...`. i belive this is mainly beacuse the lib didnt account for such values.

replacing the line with `if(!is_array($val))  $val = array($val);`
or best yet casting it to array like this `$val = (array)$val;` and removing the if, this will do nothing if the value is aready an array.

**Comment by cubiclesoft** [comment]
Nulls and booleans are invalid as HTTP POST vars.  A cast would bury obvious application errors.  Fixed by returning a standard error instead of proceeding ahead as if nothing is wrong.  I realize that PHP objects can also be cast to arrays but those aren't designed for HTTP POST either as values.  The array option is to allow for repeating names to do things such as pass an "array" to a target (e.g. `ids[]=5&ids[]=6...`).  The target application of the request, usually PHP, converts the incoming parameter names to an array.  The result is language- and target-dependent.
