### ISSUE TITLE
Issue with the final URL

### ISSUE THREAD

**Issue by hussainijaz786** [cubiclesoft/ultimate-web-scraper#26]
Hi,

I am trying to get a page from this URL: 

```php
$url = "https://www.amainhobbies.com/search/?s=ASC97003";
$web = new WebBrowser();
$result = $web->Process($url);
```

In actual, page is redirected to somewhere else, but scraper is not redirecting to the final page.
Can you please shed some light what could be the issue here?

Thank You!

**Comment by cubiclesoft** [comment]
At a cursory glance of the request stream, it looks like that site is reloading the page after setting some cookies.  Users arrive at the site without cookies set and so the page is served in such a way that sets those cookies.  Then there is a sequence of processes that set a series of other HTTP cookies that may or may not be required.  Then the page is reloaded.  One or several of the set cookies effectively results in the correct redirect to final location.

All you might need to do is send the same request twice, like this (untested):

```php
$url = "https://www.amainhobbies.com/search/?s=ASC97003";
$web = new WebBrowser();
$result = $web->Process($url);
$result = $web->Process($url);
```

Although, it might be better to be more natural so as to avoid detection:

```php
$web = new WebBrowser();

$url = "https://www.amainhobbies.com/";
$result = $web->Process($url);

$url = "https://www.amainhobbies.com/search/?s=ASC97003";
$result = $web->Process($url);
```

If that doesn't work, you'll probably have to dig in a bit to figure out which cookie or header is missing/wrong.

This issue is similar to other issues in the same vein.  As a result, I've added a whole new section to the documentation called "Advanced Troubleshooting" that may help you resolve additional problems that you might encounter.  I'm closing this issue since I'm considering it a documentation bug that is now mostly resolved but feel free to continue the discussion.
