### ISSUE TITLE
Error retrieving URL. Unable to retrieve content. Remote peer disconnected.

### ISSUE THREAD

**Issue by mbouksim** [cubiclesoft/ultimate-web-scraper#29]
Hi,
I keep getting this error when trying to access a website, It works after many refresh of the same script without any modification on the script.

Here is a screenshot with the debug mode on 
![image](https://user-images.githubusercontent.com/5030439/123697439-d0fc9a00-d854-11eb-9a8e-5a244c9a8c15.png)
and the request 

<img width="706" alt="1" src="https://user-images.githubusercontent.com/5030439/123697835-449ea700-d855-11eb-87b7-c47293d43665.png">
<img width="686" alt="2" src="https://user-images.githubusercontent.com/5030439/123697831-436d7a00-d855-11eb-9bd8-75b9abd6bc08.png">

Thank you :)

**Comment by menriquez** [comment]
so the error message is not only in a different language but its also loaded with improper characters?

that sure don't make it easy to figure out, but apparently your issues lie in the transport of the data from the remote site to your local computer.

i notice in both cases that http.php seems to be the culprit.   could it be that your connection is timing out?  maybe, since as you indicate, it only happens after several scrapes have been performed, your not resetting the connection after each scrape and its just timing out trying to get all those pages?

good luck to you.
mark

________________________________
From: mbouksim ***@***.***>
Sent: Monday, June 28, 2021 1:11 PM
To: cubiclesoft/ultimate-web-scraper ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [cubiclesoft/ultimate-web-scraper] Error retrieving URL. Unable to retrieve content. Remote peer disconnected. (#29)


Hi,
I keep getting this error when trying to access a website, It works after many refresh of the same script without any modification on the script.

Here is a screenshot with the debug mode on
[image]<https://user-images.githubusercontent.com/5030439/123697439-d0fc9a00-d854-11eb-9a8e-5a244c9a8c15.png>
and the request

[1]<https://user-images.githubusercontent.com/5030439/123697835-449ea700-d855-11eb-87b7-c47293d43665.png>

[2]<https://user-images.githubusercontent.com/5030439/123697831-436d7a00-d855-11eb-9bd8-75b9abd6bc08.png>

Thank you :)

**Comment by mbouksim** [comment]
Thank you  @menriquez for your answer and sorry for the French part in the error message the English translation is “_**An existing connection has been forcibly closed by the remote host**_”.
For the error I’m trying to scrape only one time in the code and I get this error, I have to refresh the page many times (generally 3 to 6 times) to work.
also tried it with different connection always same results

**Comment by cubiclesoft** [comment]
The multilingual error messages are probably coming from a lower level than this library.  PHP is probably just displaying localized errors from the host OS since socket errors are emitted at the OS level.

The `stream_socket_client()` error is the initial connection establishment (i.e. the connection fails to establish and no data gets sent).  Something is preventing the connection in the first place.  Although I'm not sure how `fwrite()` is being called on a broken socket (i.e. the second message).  I'd need to see an example function call to the WebBrowser class that I can replicate locally.  Showing the request from a web browser doesn't help diagnose the problem other than to tell me that the context in which the request is running is the web server user.  You should test to see if making a similar request from your own computer works versus wherever you are hosting this software.  There could be any number of issues from hitting rate limits to host restrictions to unusual connectivity requirements of the destination server.

**Comment by cubiclesoft** [comment]
Since I don't see any problems with the library itself, I'm going to close this issue.  Issue trackers are not really the place to ask for assistance/help.  If this can be traced to a bug in the library, this issue can be reopened at that time.
