### ISSUE TITLE
Help / reference / example on extracting children data inside row.

### ISSUE THREAD

**Issue by sagive** [cubiclesoft/ultimate-web-scraper#32]
My apologies if this is a weird question. I am looking for a way to "simply"
extract the values inside children - for example I have the following HTML structure
in a remote page I am scraping:

```
<article class="index25372">
    <div class="productMainDiv">
        <div class="arc1 productMainTable">
            <!-- Arc Name UP-->
            <div class="productTitleBG color2">
                <a title="example title" class="productName" href="/html5/ARCLookup.taf?_function=details&amp;_ID=25372&amp;did=2026&amp;G=9510&amp;SM=9904"><h2>Some festival</h2></a>   
                <div class="ArcDateDiv h3">08/12/2021</div>
            </div>
                
            <!-- Arc Pic -->
            <div class="picarcTD color1">
                <a title="example title" name="25372" href="/html5/arcLookup.taf?_function=details&amp;_ID=25372&amp;did=2026&amp;G=9510&amp;SM=9904">
                    <img class="picarc" src="/html5/web/2026/25372ImageFile.jpg" border="0" alt="Exampe festival">
                </a>
            </div>                        
            <!-- Arc Name do -->
                
            <!-- Arc Info -->
            <div class="infoTd color1">
                <div class="textBesidePic">
                    <div class="productDetails">
                        <p class="short-desc"> <strong>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's</strong> </p>
                        <a rel="nofollow" title="example title" class="productInfo" href="/html5/arcLookup.taf?_function=details&amp;_ID=25372&amp;did=2026&amp;G=9510&amp;SM=9904">Learn More</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</article>
```

This repeats itself across the page. I am trying to grab all instances of article, 
loop trough the information inside each of them and construct an array which I can 
later use to inject data into the database.... 

I am able to find "article" but cant seem (for example) to get the value inside 
the H2 (text value) located inside '.productTitleBG'. or that URL also located 
inside '.productTitleBG'

How can I achieve this?

I am stuck here... (more like going crazy ;))

```
<?php

// https://github.com/cubiclesoft/ultimate-web-scraper
require_once "lib/support/web_browser.php";
require_once "lib/support/tag_filter.php";


/********************************************************
**  SCRAPE EVENTS
**  todo: attach daily cron based on item ID embedded in url
********************************************************/
function scraping_galil_events($url) {

	// Retrieve the standard HTML parsing array for later use.
	$htmloptions = TagFilter::GetHTMLOptions();

	// Retrieve a URL (emulating Firefox by default).
	$web = new WebBrowser();
	$result = $web->Process($url);

    // if were ok, then parse the HTML
	if ($result["response"]["code"] == 200) {

        $html = TagFilter::Explode($result["body"], $htmloptions);
        $root = $html->Get();
        $rows = $root->Find("#ARC2 article");

        foreach ($rows as $row) {

            // how to get the text inside that H2? 
            // how to grab the link href?
            $titlewrap  = $row->Find('.productName');                   // doesnt work ;(
            $titlewrap  = $row->Find('.productName')GetPlainText();     // doesnt work ;(
            $title      = $titlewrap->Find('h2')->GetText();            // doesnt work ;(


            echo '<pre style="z-index: 999; position: relative; direction: ltr; text-align: left;"> NAME:'."<br>";
            print_r($title);
            echo '</pre>'."<br>";
        }

		exit();
	}
}


$events = scraping_galil_events('SOME URL HERE');
```

Thanks for all the hard work man... you create awesome things 😎

**Comment by cubiclesoft** [comment]
Use `current()` to access the first row of results.  Perhaps something like this:

```
$title = $row->Find('.productName h2')->current()->GetPlainText();
```

That finds all `h2` elements that are children of elements with the `.productName` class that are under the current node pointed to by `$row`, then selects the first row of results, and finally converts the result to plain text (removing any inner HTML tags).

The `Find()` method returns a set of rows.  You either iterate over the rows with `foreach` OR you can get the first row with `current()`.

Attributes in the object-oriented method are accessible by their name.  So to get the `href` of the `a` tag, you might do something like:

```
$url = $row->Find('.productName')->current()->href;
```

Again, the `current()` method selects the first row found and returns it.  At that point, attributes like `href` are accessible.

However, you might want to convert that link to an absolute URL since HTML allows relative URLs and you won't be able to do much with the URL in the document until you convert the link to an absolute URL:

```
$baseurl = $result["url"];

...

$url = $row->Find('.productName')->href;
$url = HTTP::ConvertRelativeToAbsoluteURL($baseurl, $url);
```

The pagination example in the main page has a brief usage of `current()` but it's kind of buried.  I've added an example to the first object oriented example that shows how to extract a single row of data for the purpose of accessing attributes.
