### ISSUE TITLE
Rotating Proxies

### ISSUE THREAD

**Issue by razvypp** [cubiclesoft/ultimate-web-scraper#33]
Hello,

I am having difficulties in working with rotative proxies with the library can you please give me an example on how to run them and scrape a very will protected site using them?

**Comment by cubiclesoft** [comment]
The toolkit does support HTTP proxies (i.e. not SOCKS proxies) but requires carefully constructing the request options that ultimately get passed to the HTTP class:

https://github.com/cubiclesoft/ultimate-web-scraper/blob/master/docs/http.md#httpretrievewebpageurl-options--array

Generally speaking, `proxyurl` and `proxyconnect` are the two main options:

```php
<?php
  $web = new WebBrowser();

  $options = array(
    "proxyurl" => "http://someproxy.com:5293",
//    "proxyconnect" => true
  );

  $result = $web->Process("https://thewebsite.com/blah/blah/", $options);
var_dump($result);
```

The proxy support in this library is not as robust as the rest of the library.  It works but there are some limitations:

* PHP itself does not support establishing SSL/TLS over connections that already have SSL/TLS enabled.  This only affects HTTP CONNECT proxies that support SSL/TLS connections (i.e. the initial connection to a CONNECT proxy MUST be insecure).
* Proxy connections in the library currently only support BASIC authentication.  Complex NTLM and other authentication methods are not implemented.

Based on the message on Discord chat that you left, sites that are known to be ultra-restrictive tend to also keep track of IP ranges of known global public proxies in their IP blacklists.  Tor exit nodes, for example, are known to be aggressively tracked by Cloudflare.  So depending on how aggressive the site that is defending against proxy usage is that is requiring you to regularly rotate proxies, you could find yourself fighting a difficult uphill battle.

Closing this issue since it isn't a bug in the library or the documentation.
