### ISSUE TITLE
Error retrieving URL. Unable to retrieve content. Unable to establish a connection to 'ssl://www.xxxxxxxxx.com:443'.

### ISSUE THREAD

**Issue by Romi-KS** [cubiclesoft/ultimate-web-scraper#35]
Hi,
Every thing was working fine, but now I am facing following:
"Warning: stream_socket_client(): Unable to connect to ssl://www.espn.com:443 (A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) in E:\htdocs\d\ultimate-web-scraper-master\support\http.php on line 1864

Error retrieving URL. Unable to retrieve content. Unable to establish a connection to 'ssl://www.espn.com:443'."

I tried following to fix it.
1 Used makecert.bat to issue self signed certificate. and updated on certmgr.msc
2 provided followings:
           $sslopts["varify_peer"] = false;
           $sslopts["allow_self_signed"] = true;

Please enlighten me on this. It seems to be site specific problem with espn. Can it be fixed?
Note: espn is unreal.

**Comment by cubiclesoft** [comment]
This issue is lacking a number of important details:  What specific URL are you pulling?  Does your regular web browser function?  Can you show the code you are using?  What version of PHP are you running?

I have no idea what makecert.bat is.  It is "verify_peer" not "varify_peer" (spelling mistake).  The "allow_self_signed" option is for servers that present a self-signed certificate rather than a standard CA-signed certificate chain, which means your efforts to create a self-signed cert on your local computer were not going to do anything - that, and OpenSSL doesn't read the Windows Certificate Store.  The issue appears to be related to SSL/TLS timing out during the handshake, which could be a server misconfiguration issue, some random incompatibility with the cipher suite, an outdated version of PHP (running an outdated version of OpenSSL), etc.  The list of problems involved with establishing a SSL/TLS connection are quite extensive and that's before factoring in firewalls that detect unusual behaviors and dynamically manage a blacklist.

**Comment by Romi-KS** [comment]
Thanks for the reply. Sorry for the spelling mistake- "verify_peer". 
Everything in now working fine, even though I did not correct the spelling in my code.
I will update here if the problem occurs again  &  I find anything worthwhile mentioning.
Cheers to this great library.
