### ISSUE TITLE
Scraping a page which requires a login

### ISSUE THREAD

**Issue by JVRothschild** [cubiclesoft/ultimate-web-scraper#9]
Hence there are no wiki for this, I'm using this section to ask, how can you use this library to scrape pages that require authentication first? 

I did look briefly over the Post requests method, using the postvars, but not sure about it and unfortunately the existing documentation doesn't mention anything related to this matter. 

Can you advice on this, please?

**Comment by cubiclesoft** [comment]
See the existing section in the official documentation entitled "Handling HTML Forms".  The sample code covers automated extraction of forms from the retrieved HTML (via the "extractforms" option which includes a "forms" array in the result from `Process()`), changing just the values you need in the form with `SetFormValue()`, and calling `GenerateFormRequest()` (with an optional target 'submit' button) to generate the necessary information for another `Process()` call.  It's generally a far better approach than manually building POST requests since such code is more resilient to server-side changes.  Unless the server is doing something really funky, `WebBrowser` will transparently handle cookies that are set by the server.

For extremely complex authentication paths (e.g. OAuth w/ 2FA) where you need customized user input, there's `WebBrowser::InteractiveFormFill()`.  That's an advanced topic though and rarely needed.
